apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy
  labels:
    app: nginx-deploy
spec:
  selector:
    app: nginx-deploy
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
