apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-deploy
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocal: TCP
      port: 80
      targetPort: 8080
      nodePort: 31200
